### ISSUE TITLE
3a Handle Terraform and provider installation and versioning

### ISSUE THREAD

**Issue by djdta** [djdta/Certification#18]
## Description:
Handle Terraform and provider installation and versioning

## Resources Requriements:
- [x] 1 Understand Infrastructure as Code (IaC) concepts
- [x] 2 Understand Terraform's purpose (vs other IaC)

## Tasks:
- [x] Complet task https://www.terraform.io/docs/configuration/providers.html
- [x] Complet task https://www.terraform.io/docs/configuration/terraform.html
- [x] Complete https://learn.hashicorp.com/tutorials/terraform/install-cli
- [x] Complete https://learn.hashicorp.com/tutorials/terraform/aws-build#providers

## Resources:
First Header | Second Header
------------ | -------------
Resources 1 | https://www.pluralsight.com/
Resource 2 | https://leanpub.com/terraform-certified

## Outcome:
Complete all Tasks

**Comment by djdta** [comment]
Completed
