### ISSUE TITLE
3b	Describe plug-in based architecture

### ISSUE THREAD

**Issue by djdta** [djdta/Certification#19]
## Description:
3b	Describe plug-in based architecture

## Resources Requriements:
- [x] 1 Understand Infrastructure as Code (IaC) concepts
- [x] 2 Understand Terraform's purpose (vs other IaC)

## Tasks:
- [x] Complete Task https://learn.hashicorp.com/tutorials/terraform/associate-review

## Resources:
First Header | Second Header
------------ | -------------
Resources 1 | https://www.pluralsight.com/
Resource 2 | https://leanpub.com/terraform-certified

## Outcome:
All Task are completed

**Comment by djdta** [comment]
Completed
