### ISSUE TITLE
3c	Demonstrate using multiple providers

### ISSUE THREAD

**Issue by djdta** [djdta/Certification#20]
## Description:
3c	Demonstrate using multiple providers

## Resources Requriements:
- [x] 1 Understand Infrastructure as Code (IaC) concepts
- [x] 2 Understand Terraform's purpose (vs other IaC)

## Tasks:
- [x] Complete task https://learn.hashicorp.com/tutorials/terraform/aws-build#providers

## Resources:
First Header | Second Header
------------ | -------------
R1 | https://www.pluralsight.com/
R2 | https://leanpub.com/terraform-certified

**Comment by djdta** [comment]
Completed
