### ISSUE TITLE
3d	Describe how Terraform finds and fetches providers

### ISSUE THREAD

**Issue by djdta** [djdta/Certification#21]
## Description:

3d	Describe how Terraform finds and fetches providers

## Resources Requriements:
- [x] 1 Understand Infrastructure as Code (IaC) concepts
- [x] 2 Understand Terraform's purpose (vs other IaC)

## Tasks:
- [x] Complete Task https://www.terraform.io/docs/configuration/providers.html
- [x] Complete https://learn.hashicorp.com/tutorials/terraform/aws-build#providers

## Resources:
First Header | Second Header
------------ | -------------
R1 | https://www.pluralsight.com/
R2 | https://leanpub.com/terraform-certified

## Outcome:
All Tasks to be completed

**Comment by djdta** [comment]
Completed
