### ISSUE TITLE
3e	Explain when to use and not use provisioners and when to use local-exec or remote-exec

### ISSUE THREAD

**Issue by djdta** [djdta/Certification#22]
## Description:

3e	Explain when to use and not use provisioners and when to use local-exec or remote-exec

## Resources Requriements:
- [x] 1 Understand Infrastructure as Code (IaC) concepts
- [x] 2 Understand Terraform's purpose (vs other IaC)

## Tasks:
- [x] Complete https://www.terraform.io/docs/provisioners/#provisioners-are-a-last-resort
- [x] Complete https://learn.hashicorp.com/tutorials/terraform/cloud-init
- [x] Complete https://learn.hashicorp.com/tutorials/terraform/packer

## Resources:
First Header | Second Header
------------ | -------------
R1 | https://www.pluralsight.com/
R2 | https://leanpub.com/terraform-certified

## Outcome:
All Tasks should be completed

**Comment by djdta** [comment]
Completed
