### ISSUE TITLE
4a	Given a scenario: choose when to use terraform fmt to format code

### ISSUE THREAD

**Issue by djdta** [djdta/Certification#23]
## Description:
4a Given a scenario: choose when to use terraform fmt to format code

## Resources Requriements:
- [x] 1 Understand Infrastructure as Code (IaC) concepts
- [x] 2 Understand Terraform's purpose (vs other IaC)
- [x] 3 Understand Terraform basics

## Tasks:
- [x] Complete https://www.terraform.io/docs/commands/fmt.html

## Resources:
First Header | Second Header
------------ | -------------
R1 | https://www.pluralsight.com/
R2 | https://leanpub.com/terraform-certified

## Outcome:
All Tasks to be completed

**Comment by djdta** [comment]
Issue resolved 

Study guide has been written up
