### ISSUE TITLE
1 Understand infrastructure as code (IaC) concepts

### ISSUE THREAD

**Issue by djdta** [djdta/Certification#4]
## Description:

To Understand infrastructure as code (IaC) concepts

## Requirements:
- [x] 1a Explain what IaC is
- [x] 1b Describe advantages of IaC patterns

## Tasks:
- [x] Review and take notes on https://www.terraform.io/intro/index.html#infrastructure-as-code
- [x] Review and take notes on https://www.hashicorp.com/blog/infrastructure-as-code-in-a-private-or-public-cloud
- [x] Review and take notes on https://www.hashicorp.com/resources/what-is-infrastructure-as-code
- [x] Review and take notes on https://learn.hashicorp.com/tutorials/terraform/infrastructure-as-code

## Outcome:
Completed all Tasks

**Comment by djdta** [comment]
Issue resolved Epic has been completed.
