### ISSUE TITLE
2 Understand Terraform's purpose (vs other IaC)

### ISSUE THREAD

**Issue by djdta** [djdta/Certification#5]
## Requirements:
- [x] 2a Explain multi-cloud and provider-agnostic benefits
- [x] 2b Explain the benefits of state

## Tasks:
- [x] Review and take notes from https://www.terraform.io/intro/use-cases.html#multi-cloud-deployment
- [x] Review and take notes from https://www.terraform.io/docs/state/purpose.html
- [x] Review and take notes https://learn.hashicorp.com/tutorials/terraform/infrastructure-as-code

## Outcome:

All tasks have been completed

**Comment by djdta** [comment]
Issue Closed as Completed
