### ISSUE TITLE
Monitoring and Reporting

### ISSUE THREAD

**Issue by djdta** [djdta/Certification#59]
## Description:
To complete the monitoring and reporting requirements for the exam

## Objectives:
- [x] Create and maintain metrics and alarms utilizing AWS monitoring services
- [x] Recognize and differentiate performance and availability metrics
- [x] Perform the steps necessary to remediate based on performance and availability metrics

## Tasks:
- [x] Make sure all tasks are added to this epic

## Outcome:
To complete the all tasks in this epic
