### ISSUE TITLE
3 Understand Terraform basics

### ISSUE THREAD

**Issue by djdta** [djdta/Certification#6]
## Requirements:
- [x] 3a Handle Terraform and provider installation and versioning
- [x] 3b Describe plug-in based architecture
- [x] 3c Demonstrate using multiple providers
- [x] 3d Describe how Terraform finds and fetches providers
- [x] 3e Explain when to use and not use provisioners and when to use local-exec or remote-exec 

## Tasks:
- [x] To write provider Configuration
- [x] To write a Terraform Settings for terraform
- [x] Understand a Provider block
- [x] Understand how to setup terraform directory
- [x] Use of multiple providers
- [x] Explain and understand how terraform gets the providers
- [x] Understand the use of provisioners
