### ISSUE TITLE
High Availability

### ISSUE THREAD

**Issue by djdta** [djdta/Certification#63]
## Description:
To complete the monitoring and reporting requirements for the exam

## Requirements:
- [x] Access Plurasight
- [x] Implement scalability and elasticity based on use case
- [x] Recognize and differentiate highly available and resilient environments on AWS

## Tasks:
- [x] Implementing AWS EC2 Auto Scaling
- [x] Auto Scaling AWS Resources
- [x] Implementing AWS Load Balancing
- [x] Read HA Topic in SysOps

## Outcome: 
- [x] Make sure all tasks have been completed

**Comment by djdta** [comment]
All tasks have been completed and code has been merged
