### ISSUE TITLE
Auto Scaling AWS Resources

### ISSUE THREAD

**Issue by djdta** [djdta/Certification#64]
## Description:
To go through the topic of Auto Scaling AWS Resources

## Requirements:
- [x] Access to Plurasight

## Tasks:
- [x] Complete Auto Scaling AWS Resources training

## Outcome:
- [x] Completed Auto Scaling AWS Resources

**Comment by djdta** [comment]
Training material has been completed
