### ISSUE TITLE
Implementing AWS Load Balancing

### ISSUE THREAD

**Issue by djdta** [djdta/Certification#65]
## Description:
Go through the topic of Implementing AWS Load Balancing

## Requirements:
- [x] Access Plurasight training

## Tasks:
- [x] Implementing AWS Load Balancing

## Outcome:
- [x] Complete Implementing AWS Load Balancing

**Comment by djdta** [comment]
Completed the training for material for this.
