### ISSUE TITLE
Deployment and Provisioning

### ISSUE THREAD

**Issue by djdta** [djdta/Certification#66]
## Description:
To complete the monitoring and reporting requirements for the exam

## Requirements:
- [x] Access Plurasight

## Tasks:
- [x] Identify and execute steps required to provision cloud resources
- [x] Identify and remediate deployment issues

## Outcome:
- [x] To complete all tasks

**Comment by djdta** [comment]
All Tasks have been completed and notes have been taken for further studying.
