### ISSUE TITLE
Identify and remediate deployment issues

### ISSUE THREAD

**Issue by djdta** [djdta/Certification#74]
## Description:
Go through the Identify and remediate deployment issues material

## Requirements:
- [ ] Access to Plurasight

## Tasks:
- [ ] Identify and remediate deployment issues

## Outcome:
- [ ] To complete the Identify and remediate deployment issues material
