### ISSUE TITLE
Implement and manage security policies on AWS

### ISSUE THREAD

**Issue by djdta** [djdta/Certification#75]
## Description:
Go through the Implement and manage security policies on AWS material

## Requirements:
- [x] Access Plurasight Platform

## Tasks:
- [x] Implement and manage security policies on AWS

## Outcome:
- [x] Completed Implement and manage security policies on AWS material

**Comment by djdta** [comment]
Completed the topic and added my notes
