### ISSUE TITLE
Implement access controls when using AWS

### ISSUE THREAD

**Issue by djdta** [djdta/Certification#76]
## Description:
Go through the Implement access controls when using AWS material

## Requirements:
- [ ] Access Plurasight platform

## Tasks:
- [ ] Implement access controls when using AWS

## Outcome:
- [ ] To complete Implement access controls when using AWS
