### ISSUE TITLE
Differentiate between the roles and responsibility within the shared responsibility model

### ISSUE THREAD

**Issue by djdta** [djdta/Certification#77]
## Description:
Go through the Differentiate between the roles and responsibility within the shared responsibility model material

## Requirements:
- [x] Access Plurasight Platform

## Tasks:
- [x] Differentiate between the roles and responsibility within the shared responsibility model

## Outcome:
- [x] To complete Differentiate between the roles and responsibility within the shared responsibility model

**Comment by djdta** [comment]
Completed topic
