### ISSUE TITLE
Apply AWS networking features

### ISSUE THREAD

**Issue by djdta** [djdta/Certification#79]
## Description:
Go through the Apply AWS networking features training material

## Requirements:
- [ ] Access Plurasight platform

## Tasks:
- [ ] Apply AWS networking features

## Outcome:
- [ ] To complete Apply AWS networking features
