### ISSUE TITLE
Implement connectivity services of AWS

### ISSUE THREAD

**Issue by djdta** [djdta/Certification#80]
## Description:
Go through the Implement connectivity services of AWS materail

## Requirements:
- [ ] Access Plurasight Platform

## Tasks:
- [ ] Implement connectivity services of AWS

## Outcome:
- [ ] To complete Implement connectivity services of AWS
