### ISSUE TITLE
Gather and interpret relevant information for network troubleshooting

### ISSUE THREAD

**Issue by djdta** [djdta/Certification#81]
## Description:
Go through the Gather and interpret relevant information for network troubleshooting material

## Requirements:
- [ ] Access Plurasight platform

## Tasks:
- [ ] Gather and interpret relevant information for network troubleshooting

## Outcome:
- [ ] To complete Gather and interpret relevant information for network troubleshooting
