### ISSUE TITLE
Use AWS services and features to manage and assess resource utilization

### ISSUE THREAD

**Issue by djdta** [djdta/Certification#82]
## Description:
Go through the Use AWS services and features to manage and assess resource utilization training material

## Requirements:
- [ ] Access Plurasight platform

## Tasks:
- [ ] Use AWS services and features to manage and assess resource utilization

## Outcome:
- [ ] To complete tasks
