### ISSUE TITLE
Employ cost-optimization strategies for efficient resource utilization

### ISSUE THREAD

**Issue by djdta** [djdta/Certification#83]
## Description:
Go through the Employ cost-optimization strategies for efficient resource utilization training material

## Requirements:
- [ ] Access to Plurasight

## Tasks:
- [ ] Employ cost-optimization strategies for efficient resource utilization

## Outcome:
- [ ] To complete all tasks
