### ISSUE TITLE
AWS Certified SysOps Administrator

### ISSUE THREAD

**Issue by djdta** [djdta/Certification#88]
## Description:
To book this exam in to been taken after all objectives have been done

## Requirements:
- [ ] Monitoring and Reporting
- [ ] High Availability
- [ ] Deployment and Provisioning
- [ ] Storage and Data Management
- [ ] Security and Compliance
- [ ] Networking
- [ ] Automation and Optimization

## Tasks:
- [ ] Book Exam

## Outcome:
- [ ] Exam Passed
