### ISSUE TITLE
Read HA Chapter

### ISSUE THREAD

**Issue by djdta** [djdta/Certification#89]
## Description:
Please read the HA topic in the study guide book

## Requirements:
 - [ ] Sybex SysOps AWS

## Tasks:
- [ ] Read HA Topic in the study guide

## Outcome:
- [ ] Completed the Study guide section.

**Comment by djdta** [comment]
Completed reading on Study Topic
